#!/usr/bin/env python3
"""
Generate Fantasy Cycling Data
==============================

This script fetches real rider data from CyclingFlash and generates
a JavaScript/TypeScript file for use in a React fantasy cycling app.

Usage:
    python generate_fantasy_data.py [--limit 50] [--output riders.tsx]

Output:
    A TypeScript file with rider data ready to import into React.
"""

import argparse
import json
import sys
sys.path.insert(0, '/home/claude')

from cyclingflash_api import FantasyManager, Ranking


def generate_riders_data(limit: int = 50, gender: str = 'men-elite') -> list:
    """Generate rider data from CyclingFlash rankings."""
    
    print(f"Fetching top {limit} riders from CyclingFlash...")
    
    fm = FantasyManager()
    riders = fm.get_top_riders(limit, gender)
    
    print(f"Found {len(riders)} riders")
    
    return riders


def export_as_tsx(riders: list, output_file: str = None) -> str:
    """Export riders as TypeScript React component data."""
    
    # Group riders by value tier for comments
    tiers = {
        'Super Elite (45-60M €)': [],
        'Elite A (35-44M €)': [],
        'Elite B (25-34M €)': [],
        'Elite C (20-24M €)': [],
        'Elite D (15-19M €)': [],
        'Elite E (10-14M €)': [],
        'Strong A (8-9M €)': [],
        'Strong B (6-7M €)': [],
        'Strong C (4-5M €)': [],
        'Solid (1-3M €)': [],
    }
    
    for rider in riders:
        v = rider['value']
        if v >= 45:
            tiers['Super Elite (45-60M €)'].append(rider)
        elif v >= 35:
            tiers['Elite A (35-44M €)'].append(rider)
        elif v >= 25:
            tiers['Elite B (25-34M €)'].append(rider)
        elif v >= 20:
            tiers['Elite C (20-24M €)'].append(rider)
        elif v >= 15:
            tiers['Elite D (15-19M €)'].append(rider)
        elif v >= 10:
            tiers['Elite E (10-14M €)'].append(rider)
        elif v >= 8:
            tiers['Strong A (8-9M €)'].append(rider)
        elif v >= 6:
            tiers['Strong B (6-7M €)'].append(rider)
        elif v >= 4:
            tiers['Strong C (4-5M €)'].append(rider)
        else:
            tiers['Solid (1-3M €)'].append(rider)
    
    # Generate TypeScript
    lines = [
        "// Auto-generated from CyclingFlash data",
        "// Generated by cyclingflash_api",
        "",
        "export interface Rider {",
        "  id: number;",
        "  name: string;",
        "  team: string;",
        "  value: number;",
        "  expectedPoints: number;",
        "  selected: boolean;",
        "}",
        "",
        "export const riders: Rider[] = [",
    ]
    
    for tier_name, tier_riders in tiers.items():
        if tier_riders:
            lines.append(f"    // {tier_name}")
            for rider in tier_riders:
                name = rider['name'].replace('"', '\\"')
                team = rider['team'].replace('"', '\\"')
                lines.append(f'    {{ id: {rider["id"]}, name: "{name}", team: "{team}", value: {rider["value"]}, expectedPoints: {rider["expectedPoints"]}, selected: false }},')
            lines.append("")
    
    lines.append("];")
    lines.append("")
    lines.append("export default riders;")
    
    content = "\n".join(lines)
    
    if output_file:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Saved to {output_file}")
    
    return content


def export_as_json(riders: list, output_file: str = None) -> str:
    """Export riders as JSON."""
    
    content = json.dumps(riders, indent=2, ensure_ascii=False)
    
    if output_file:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Saved to {output_file}")
    
    return content


def main():
    parser = argparse.ArgumentParser(description='Generate fantasy cycling data')
    parser.add_argument('--limit', type=int, default=50, 
                        help='Number of riders to fetch')
    parser.add_argument('--output', type=str, default='riders.tsx',
                        help='Output file name')
    parser.add_argument('--format', choices=['tsx', 'json'], default='tsx',
                        help='Output format')
    parser.add_argument('--gender', choices=['men-elite', 'women-elite'], 
                        default='men-elite', help='Gender category')
    
    args = parser.parse_args()
    
    try:
        riders = generate_riders_data(args.limit, args.gender)
        
        if args.format == 'tsx':
            content = export_as_tsx(riders, args.output)
        else:
            content = export_as_json(riders, args.output)
        
        print("\nSample output:")
        print("-" * 40)
        print(content[:1000] + "..." if len(content) > 1000 else content)
        
    except Exception as e:
        print(f"Error: {e}")
        print("\nNote: This script requires internet access to fetch data from CyclingFlash.")
        print("Run this script in an environment with network access.")
        
        # Generate sample data for testing
        print("\nGenerating sample data instead...")
        sample_riders = [
            {"id": 1, "name": "Tadej Pogačar", "team": "UAE Emirates XRG", "value": 60, "expectedPoints": 6500, "selected": False},
            {"id": 2, "name": "Jonas Vingegaard", "team": "Team Visma | Lease a Bike", "value": 55, "expectedPoints": 6000, "selected": False},
            {"id": 3, "name": "Remco Evenepoel", "team": "Soudal - Quick Step", "value": 50, "expectedPoints": 5500, "selected": False},
            {"id": 4, "name": "Mathieu van der Poel", "team": "Alpecin - Premier Tech", "value": 44, "expectedPoints": 4500, "selected": False},
            {"id": 5, "name": "Wout van Aert", "team": "Team Visma | Lease a Bike", "value": 42, "expectedPoints": 4000, "selected": False},
        ]
        
        if args.format == 'tsx':
            content = export_as_tsx(sample_riders, args.output)
        else:
            content = export_as_json(sample_riders, args.output)
        
        print(content)


if __name__ == '__main__':
    main()
